all: build

build:
	docker buildx build --platform linux/arm64 --pull -t registry.bizsaas.net/arm64v8/domeos/agent:2.5 -f Dockerfile.arm64v8 .

push:
	docker push registry.bizsaas.net/arm64v8/domeos/agent:2.5

.PHONY: all build push